# Alt-上矢印キーでウィンドウの新規作成
bind -n S-up new-window -c "#{pane_current_path}"

# Alt-下矢印キーでウィンドウの削除
bind -n S-down confirm-before 'kill-window'

# Alt-右左矢印キーでウィンドウの切り替え
bind -n S-left previous-window
bind -n S-right next-window

# Alt-- でウィンドウの分割[水平]
bind -n  S-- split-window -vc "#{pane_current_path}"

# Alt-\ でウィンドウの分割[垂直]
# ( | で垂直分割としたいが|は入力にShiftが必要なため省略)
bind -n 'S-\' split-window -hc "#{pane_current_path}"

# コピーモードへの切り替え (Ctrl-上矢印キー)
bind -n C-up copy-mode

# mouse on
set-option -g mouse on

# copy-mode vi
set-option -gw mode-keys vi
set -s set-clipboard on
bind -n C-y copy-mode
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel 'xsel --clipboard --input'
