vim.keymap.set("n", "<C-h>", "<cmd>Neotree action=focus<CR>")
vim.keymap.set("n", "<C-l>", "<cmd>wincmd p<CR>")
vim.keymap.set("n", "<S-h>", "<cmd>tabprev<CR>")
vim.keymap.set("n", "<S-l>", "<cmd>tabnext<CR>")

local builtin = require("telescope.builtin")
vim.keymap.set('n', '<leader>ff', builtin.find_files, { desc = 'Telescope find files' })
vim.keymap.set('n', '<leader>fw', builtin.live_grep, { desc = 'Telescope live grep' })
vim.keymap.set('n', '<leader>fb', builtin.buffers, { desc = 'Telescope buffers' })
vim.keymap.set('n', '<leader>fh', builtin.help_tags, { desc = 'Telescope help tags' })
