vim.keymap.set("n", "<C-h>", "<cmd>Neotree action=focus<CR>")
vim.keymap.set("n", "<C-l>", "<cmd>wincmd p<CR>")
vim.keymap.set("n", "<S-h>", "<cmd>tabprev<CR>")
vim.keymap.set("n", "<S-l>", "<cmd>tabnext<CR>")

local builtin = require("telescope.builtin")
vim.keymap.set('n', '<leader>ff', builtin.find_files, { desc = 'Telescope find files' })
vim.keymap.set('n', '<leader>fw', builtin.live_grep, { desc = 'Telescope live grep' })
vim.keymap.set('n', '<leader>fb', builtin.buffers, { desc = 'Telescopej: buffers' })
vim.keymap.set('n', '<leader>fh', builtin.help_tags, { desc = 'Telescope help tags' })

vim.keymap.set({ 'n', 'v' }, 'd', '"_d')
vim.keymap.set({ 'n', 'v' }, 'dd', '"_dd')
vim.keymap.set({ 'n', 'v' }, 'x', '"_x')
vim.keymap.set({ 'n', 'v' }, 'd', '"_d')
vim.keymap.set({ 'n', 'v' }, 'ciw', '"_ciw')
vim.keymap.set({ 'n', 'v' }, 'diw', '"_diw')
vim.keymap.set({ 'n', 'v' }, 'dw', '"_dw')
